### ISSUE TITLE
master builds broken (missing ressources)

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#18257]
Latest master is not building due to changes introduced in https://github.com/cgeo/cgeo/pull/18244

/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:84: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.map_map, R.drawable.sc_map, new Intent(this, UnifiedMapActivity.class), ID_FRAGMENT_MAP));
                                                               ^
  symbol:   variable sc_map
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:85: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.caches_nearby_button, R.drawable.sc_nearby, CacheListActivity.getNearestIntent(this), ID_FRAGMENT_NEARBY));
                                                                            ^
  symbol:   variable sc_nearby
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:91: error: cannot find symbol
        final Shortcut offlineShortcut = new Shortcut(R.string.list_title, R.drawable.sc_stored, null, ID_FRAGMENT_LIST);
                                                                                     ^
  symbol:   variable sc_stored
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:95: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.list_all_lists, R.drawable.sc_stored, allIntent, ID_FRAGMENT_ALL_CACHES));
                                                                      ^
  symbol:   variable sc_stored
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:96: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.advanced_search_button, R.drawable.sc_search, new Intent(this, SearchActivity.class), ID_FRAGMENT_SEARCH));
                                                                              ^
  symbol:   variable sc_search
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:99: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.wherigo_player, R.drawable.sc_wherigo, new Intent(this, WherigoActivity.class), ID_FRAGMENT_WHERIGO));
                                                                      ^
  symbol:   variable sc_wherigo
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:128: error: cannot find symbol
        createShortcutAndFinish(list.title, targetIntent, R.drawable.sc_stored, ID_FRAGMENT_LIST + list.id);
                                                                    ^
  symbol:   variable sc_stored

**Comment by moving-bits** [comment]
That's strange, both local build and the related PR have been green. Maybe some gradle caching issue - have you tried clearing the cache + rebuilding all c:geo files?

**Comment by ztNFny** [comment]
> That's strange, both local build and the related PR have been green. Maybe some gradle caching issue - have you tried clearing the cache + rebuilding all c:geo files?

Cleared everything, even did a checkout to a new directory.

**Comment by moving-bits** [comment]
I have not been able to reproduce this issue yet. This is what I have tried so far:
- Rebuild current project (`master` branch)
- Cleared all AS caches, "clean project", "Compile all sources"
- Create a new folder, clone my fork, set upstream remote, rebase to upstream master

All of those builds worked flawlessly for me, and lead to new build being installed in the emulator, running fine.

I'm running AS Quail 1 / 2026.1.1 Patch 1.

Can you retry after having deleted `cgeo/main/build` (with all subfolders)?

**Comment by moving-bits** [comment]
Technically, having drawables with identical names both in folder `drawable-v26` and `drawable` just means, that from API level 26 onward it will take the `drawable-v26` version, otherwise the `drawable`.

Since c:geo uses minSDK 26 meanwhile (on branch `master`, the versions in `drawable` are never used anymore in our `master` version, and since the drawables in `drawable-v26` cannot stand on their own, I moved them to `drawable`. This is pretty basic Android procedure - but I may have missed something.

I remember AS having such kind of "hiccups" from time to time, generally with no specific reason (at least none known to me). Ways to resolve this have been different for me over the years, sometimes clearing caches helped, sometimes removing `.gradle` or `build` folders, sometimes even an AS update.

**Comment by ztNFny** [comment]
rm -rf build-cache/ finally did it.
I had done .gradle, build, main/build and all the AS clear stuff before
