### PR TITLE
undo moving resources which broke gradle builds

### LINKED ISSUE #18257: master builds broken (missing ressources)
Latest master is not building due to changes introduced in https://github.com/cgeo/cgeo/pull/18244

/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:84: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.map_map, R.drawable.sc_map, new Intent(this, UnifiedMapActivity.class), ID_FRAGMENT_MAP));
                                                               ^
  symbol:   variable sc_map
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:85: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.caches_nearby_button, R.drawable.sc_nearby, CacheListActivity.getNearestIntent(this), ID_FRAGMENT_NEARBY));
                                                                            ^
  symbol:   variable sc_nearby
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:91: error: cannot find symbol
        final Shortcut offlineShortcut = new Shortcut(R.string.list_title, R.drawable.sc_stored, null, ID_FRAGMENT_LIST);
                                                                                     ^
  symbol:   variable sc_stored
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:95: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.list_all_lists, R.drawable.sc_stored, allIntent, ID_FRAGMENT_ALL_CACHES));
                                                                      ^
  symbol:   variable sc_stored
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:96: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.advanced_search_button, R.drawable.sc_search, new Intent(this, SearchActivity.class), ID_FRAGMENT_SEARCH));
                                                                              ^
  symbol:   variable sc_search
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:99: error: cannot find symbol
        shortcuts.add(new Shortcut(R.string.wherigo_player, R.drawable.sc_wherigo, new Intent(this, WherigoActivity.class), ID_FRAGMENT_WHERIGO));
                                                                      ^
  symbol:   variable sc_wherigo
  location: class drawable
/cgeo/main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java:128: error: cannot find symbol
        createShortcutAndFinish(list.title, targetIntent, R.drawable.sc_stored, ID_FRAGMENT_LIST + list.id);
                                                                    ^
  symbol:   variable sc_stored

### PR DESCRIPTION
**Pull request by ztNFny**
partially reverts the changes from https://github.com/cgeo/cgeo/pull/18244 which broke builds on master

### CODE REVIEW

**Comment by moving-bits** [comment]
I can have a look at it tonight.
