### ISSUE TITLE
Build fails with fault in Datastore

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8103]
Since merging the related PR the building fails on CI:
@moving-bits 

integration/main/src/cgeo/geocaching/storage/DataStore.java:3784: error: cannot find symbol
13:08:29  
13:08:29                  statement.bindString    (1, InternalConnector.GEOCODE_HISTORY_CACHE);  // geocode
13:08:29                                              ^
13:08:29    symbol:   variable InternalConnector
13:08:29    location: class DataStore

**Comment by moving-bits** [comment]
Seems to be a merge artifact - fixed it with #8104

**Comment by moving-bits** [comment]
closed with #8104
