### ISSUE TITLE
send2cgeo script does'nt work in Iceweasel (Firefox) 3.5.16

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#293]
I recently decided to try send2cgeo, but i cant  install greasemonkey script, it says "Script could not be installed TypeError: this._initScriptDir is not a function".

Thanks
