### ISSUE TITLE
Crash on About:License?

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5035]
First crash report for new version (2015.06.15). Not sure how relevant that is, but it is shown as 'new' (so kind-of regression). It was on a HTC One S (ville) with Android 4.1.

```
java.lang.IncompatibleClassChangeError: interface not implemented
at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
at cgeo.geocaching.AboutActivity$LicenseViewCreator.getRawResourceString(AboutActivity.java:63)
at cgeo.geocaching.AboutActivity$LicenseViewCreator.getDispatchedView(AboutActivity.java:51)
at cgeo.geocaching.AboutActivity$LicenseViewCreator.getDispatchedView(AboutActivity.java:41)
at cgeo.geocaching.ui.AbstractCachingPageViewCreator.getView(AbstractCachingPageViewCreator.java:30)
at cgeo.geocaching.activity.AbstractViewPagerActivity$ViewPagerAdapter.instantiateItem(AbstractViewPagerActivity.java:161)
at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:837)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1053)
at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
at android.support.v4.view.ViewPager$3.run(ViewPager.java:249)
at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1766)
at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1901)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1833)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1888)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1888)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1888)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1888)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2046)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1500)
at android.app.Activity.dispatchTouchEvent(Activity.java:2454)
at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.dispatchTouchEvent(ActionBarActivityDelegateICS.java:268)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1994)
at android.view.View.dispatchPointerEvent(View.java:7392)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3556)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3485)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4594)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4573)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4669)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:184)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:131)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:5454)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mucek4** [comment]
4 crashes up to now, Android 4.0, 4.1
Z796C (Z796C)
HTC One S (ville)
Xperia Miro (ST23i)
Galaxy Xcover2 (skomer)

**Comment by Lineflyer** [comment]
We have one similar report on FB: c:geo crashes when trying to view the Contributor list.

**Comment by Lineflyer** [comment]
Can reproduce on one of my devices:

```
--- System information ---
Device: ZTE Grand Memo LTE (Grand-Memo, ZTE) 
Android version: 4.1.2 
Android build: GEN_EU_GRANDMEMOLTEV1.0.0B06 
Cgeo version: 2015.06.15
 Google Play services: enabled
 Low power mode: inactive 
Compass capabilities: yes 
Rotation sensor: present 
Geomagnetic rotation sensor: absent 
Orientation sensor: present 
Hide own/found: true 
Map strategy: auto HW acceleration: disabled (default state) 
System language: en_US 
Geocaching sites enabled:
 geocaching.com: logged in (Login OK) / Premium
 Installed cgeo plugins: calendar
--- End of system information ---
```

```
09:43:55.367 Error cgeo 19482  [main] UncaughtException
09:43:55.367 Error cgeo 19482  java.lang.IncompatibleClassChangeError: interface not implemented
09:43:55.367 Error cgeo 19482  	at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
09:43:55.367 Error cgeo 19482  	at cgeo.geocaching.AboutActivity$LicenseViewCreator.getRawResourceString(AboutActivity.java:63)
09:43:55.367 Error cgeo 19482  	at cgeo.geocaching.AboutActivity$LicenseViewCreator.getDispatchedView(AboutActivity.java:51)
09:43:55.367 Error cgeo 19482  	at cgeo.geocaching.AboutActivity$LicenseViewCreator.getDispatchedView(AboutActivity.java:41)
09:43:55.367 Error cgeo 19482  	at cgeo.geocaching.ui.AbstractCachingPageViewCreator.getView(AbstractCachingPageViewCreator.java:30)
09:43:55.367 Error cgeo 19482  	at cgeo.geocaching.activity.AbstractViewPagerActivity$ViewPagerAdapter.instantiateItem(AbstractViewPagerActivity.java:161)
09:43:55.367 Error cgeo 19482  	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:837)
09:43:55.367 Error cgeo 19482  	at android.support.v4.view.ViewPager.populate(ViewPager.java:1053)
09:43:55.367 Error cgeo 19482  	at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
09:43:55.367 Error cgeo 19482  	at android.support.v4.view.ViewPager$3.run(ViewPager.java:249)
09:43:55.367 Error cgeo 19482  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
09:43:55.367 Error cgeo 19482  	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
09:43:55.367 Error cgeo 19482  	at android.view.Choreographer.doFrame(Choreographer.java:524)
09:43:55.367 Error cgeo 19482  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
09:43:55.367 Error cgeo 19482  	at android.os.Handler.handleCallback(Handler.java:615)
09:43:55.367 Error cgeo 19482  	at android.os.Handler.dispatchMessage(Handler.java:92)
09:43:55.367 Error cgeo 19482  	at android.os.Looper.loop(Looper.java:137)
09:43:55.367 Error cgeo 19482  	at android.app.ActivityThread.main(ActivityThread.java:4797)
09:43:55.367 Error cgeo 19482  	at java.lang.reflect.Method.invokeNative(Native Method)
09:43:55.367 Error cgeo 19482  	at java.lang.reflect.Method.invoke(Method.java:511)
09:43:55.367 Error cgeo 19482  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
09:43:55.367 Error cgeo 19482  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
09:43:55.367 Error cgeo 19482  	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Bananeweizen** [comment]
Seems that was there before: #3515

**Comment by rsudev** [comment]
Re-introduced in 702094e8bbda76a12b0673a61ca86b811a6a75fd on April, 1st

**Comment by samueltardieu** [comment]
Feel free to revert. But still, this is really unclean.

**Comment by rsudev** [comment]
A quick research seems to indicate, that Scanner does not implement Closable on Android 4.1, so we need to close 'manually' instead. But that shouldn't be an issue in itself?

**Comment by rsudev** [comment]
Implemented a fix based on release, merged to master first for testing.

**Comment by rsudev** [comment]
Scheduled NB1 for testing

**Comment by Lineflyer** [comment]
Tested and OK with the device "ZTE Grand Memo LTE" on Android 4.1.2 with 2015.06.16-NB1
and still working on "Samsung S4" on Android 5.0.2 with 2015.06.16-NB1.

Assigning to @rsudev for merge to release.

**Comment by rsudev** [comment]
Merged.
