### ISSUE TITLE
tests still failing on compile SDK 28

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7878]
Even with #7870 and #7871 included tests fail after upgrading _compile_ SDK to 28, see https://ci.cgeo.org/job/cgeo%20pull%20request/2325/consoleFull#-109812861545fc375f-a63e-468b-8450-76255356fdf9:

```
> Task :main:compileBasicDebugAndroidTestJavaWithJavac FAILED
16:51:04  /home/jenkins/slave/workspace/cgeo pull request/tests/src-android/cgeo/CGeoTestCase.java:9: error: package android.test does not exist
16:51:04  import android.test.ApplicationTestCase;
16:51:04                     ^
16:51:04  /home/jenkins/slave/workspace/cgeo pull request/tests/src-android/cgeo/CGeoTestCase.java:13: error: cannot find symbol
16:51:04  public abstract class CGeoTestCase extends ApplicationTestCase<CgeoApplication> {
16:51:04                                             ^
16:51:04    symbol: class ApplicationTestCase
16:51:04  /home/jenkins/slave/workspace/cgeo pull request/tests/src-android/cgeo/geocaching/test/AbstractResourceInstrumentationTestCase.java:20: error: package android.test does not exist
16:51:04  import android.test.InstrumentationTestCase;
16:51:04                     ^
16:51:04  /home/jenkins/slave/workspace/cgeo pull request/tests/src-android/cgeo/geocaching/test/AbstractResourceInstrumentationTestCase.java:32: error: cannot find symbol
16:51:04  public abstract class AbstractResourceInstrumentationTestCase extends InstrumentationTestCase {
16:51:04                                                                        ^
16:51:04    symbol: class InstrumentationTestCase
16:51:04  /home/jenkins/slave/workspace/cgeo pull request/tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java:28: error: package android.test.suitebuilder.annotation does not exist
...
```

@bekuno  Can you have a look at it?

**Comment by bekuno** [comment]
I have a solution.

**Comment by moving-bits** [comment]
@bekuno
Thanks for fixing. By this we've finally reached API level 28 in targetSDK, compileSDK and supportLib!
