### PR TITLE
Geocache annotations and cleanup

### PR DESCRIPTION
**Pull request by NotWoods**
## Description

Adds more `@Nullable` and `@NotNull` annotations and catches a few potential null errors.

Adds DrawableRes annotations to mark certain ints as drawable resource IDs.

Replaces searchContext with a single finder field so its clear what's being stored, instead of a untyped Bundle.

### CODE REVIEW

**Comment by fm-sys** [comment]
FYI, there are some compile errors in the unit tests... 

```
06:13:24  /home/jenkins/slave/workspace/cgeo-CI_PR-build/tests/src-android/cgeo/geocaching/SearchResultTest.java:32: error: cannot find symbol
06:13:24          search.getSearchContext().putString("testkey", "test");
06:13:24                ^
06:13:24    symbol:   method getSearchContext()
06:13:24    location: variable search of type SearchResult
06:13:24  /home/jenkins/slave/workspace/cgeo-CI_PR-build/tests/src-android/cgeo/geocaching/SearchResultTest.java:39: error: no suitable constructor found for SearchResult(Parcel)
06:13:24          final SearchResult receive = new SearchResult(parcel);
06:13:24                                       ^
06:13:24      constructor SearchResult.SearchResult(SearchResult) is not applicable
06:13:24        (argument mismatch; Parcel cannot be converted to SearchResult)
06:13:24      constructor SearchResult.SearchResult(Set<String>) is not applicable
06:13:24        (argument mismatch; Parcel cannot be converted to Set<String>)
06:13:24      constructor SearchResult.SearchResult(Geocache) is not applicable
06:13:24        (argument mismatch; Parcel cannot be converted to Geocache)
06:13:24      constructor SearchResult.SearchResult(Collection<Geocache>) is not applicable
06:13:24        (argument mismatch; Parcel cannot be converted to Collection<Geocache>)
06:13:25  /home/jenkins/slave/workspace/cgeo-CI_PR-build/tests/src-android/cgeo/geocaching/SearchResultTest.java:50: error: cannot find symbol
06:13:25          assertThat(receive.getSearchContext().getString("testkey")).isEqualTo("test");
06:13:25                            ^
06:13:25    symbol:   method getSearchContext()
06:13:25    location: variable receive of type SearchResult 
```

**Comment by fm-sys** [comment]
Hi @NotWoods, there are some merge conflicts with need to be solved before the PR can be merged... Thank you!

**Review by fm-sys — APPROVED** [review]
Adding annotations is always a good thing, so LGTM.

I'm not familiar with the `searchContext/finder` code part. At a quick glance it looks good, however I haven't yet discovered the real use of it at all... Someone should IMHO do a quick test in the emulator before merging (if search-by-finder is still working as expected).

**Comment by jakedot** [comment]
is someone merging those changes?

**Comment by moving-bits** [comment]
> Someone should IMHO do a quick test in the emulator before merging (if search-by-finder is still working as expected).

Did a _very short_ test of "search by finder" - seems to work fine over here.

Regarding `searchContext`: It got introduced with 48fd8c0391f9caf131cbd1d33c8a1dbaacb9e60d by @eddiemuc - maybe he can cross-check whether the changes in this PR are ok?

**Comment by eddiemuc** [comment]
> Regarding `searchContext`: It got introduced with 48fd8c0391f9caf131cbd1d33c8a1dbaacb9e60d by @eddiemuc - maybe he can cross-check whether the changes in this PR are ok?

The idea behind this was to introduce a generic mechanism so one could store other search-context-values in the future if need be. With this change this is no longer possible.

I am not insisting on keeping the bundle though.

**Comment by NotWoods** [comment]
A data class would be nicer as a generic mechanism IMO, since you would have clear input/output types. I can switch to a class w/ one field or leave as is

**Comment by eddiemuc** [comment]
> A data class would be nicer as a generic mechanism IMO, since you would have clear input/output types. I can switch to a class w/ one field or leave as is

This would bring the overhead to make said class `Parcelable`, I wanted to spare this overhead (which is why I chose to use a Bundle in the first place). Anyway, as said, I have no strong opinion on this - please proceed as you prefer.

**Comment by moving-bits** [comment]
FYI: Whatever direction you'll prefer to take wrt bundle / data class / plain string: This PR needs yet another rebase with conflict resolution to be able to be merged.

**Comment by NotWoods** [comment]
Merged!

**Comment by moving-bits** [comment]
Thanks @NotWoods for your PR and for your patience...
